name: ica
channels:
  - conda-forge
  - defaults
dependencies:
- python>=3.7
- numpy
- pandas
- scipy
- matplotlib
- pytest
- pip
- tqdm
- seaborn
- black
- ipython
- jupyterlab
- scikit-learn
- jupytext
- htop  # no more black bars in htop in tmux on remote cluster
- flake8
- pip:
  - pytest-cov 
  - jax